name: Commit
on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-22.04
          - macos-13
          - windows-2022
    steps:
      - name: Fetch source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 17
          # will restore cache of dependencies and wrappers
          cache: 'gradle'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build Debug APK
        run: |
          ./gradlew :app:assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: foxy-droid-${{ matrix.os }}
          path: app/build/outputs/apk/debug/
          retention-days: 10
